### ISSUE TITLE
Visualization Import Errors

### ISSUE THREAD

**Issue by saadehmd** [BerkeleyAutomation/visualization#11]
I get the following errors whenever i try to import anything from visualization module:
I tried reinstalling/upgrading/downgrading , but no luck.
Traceback (most recent call last):
  File "render_images.py", line 19, in <module>
    from visualization import Visualizer2D as vis
  File "/home/ahmad3/anaconda2/envs/gpd/lib/python2.7/site-packages/visualization/__init__.py", line 3, in <module>
    from .visualizer3d import Visualizer3D
  File "/home/ahmad3/anaconda2/envs/gpd/lib/python2.7/site-packages/visualization/visualizer3d.py", line 9, in <module>
    from pyrender import Scene, Mesh, Viewer, Node, MetallicRoughnessMaterial, TextAlign
  File "/home/ahmad3/anaconda2/envs/gpd/lib/python2.7/site-packages/pyrender/__init__.py", line 12, in <module>
    from .viewer import Viewer
  File "/home/ahmad3/anaconda2/envs/gpd/lib/python2.7/site-packages/pyrender/viewer.py", line 36, in <module>
    class Viewer(pyglet.window.Window):
  File "/home/ahmad3/anaconda2/envs/gpd/lib/python2.7/site-packages/pyglet/__init__.py", line 335, in __getattr__
    __import__(import_name)
  File "/home/ahmad3/anaconda2/envs/gpd/lib/python2.7/site-packages/pyglet/window/__init__.py", line 131, in <module>
    import pyglet.window.event
  File "/home/ahmad3/anaconda2/envs/gpd/lib/python2.7/site-packages/pyglet/window/event.py", line 74
    key.symbol_string(symbol), key.modifiers_string(modifiers)), file=self.file)

**Comment by mjd3** [comment]
Hey @saadehmd, I think the issue here lies with pyglet; as stated [here](https://github.com/pyglet/pyglet): "Pyglet runs under Python 3.5+." You appear to be running Python 2.7. Your options are to either downgrade your pyrender/pyglet versions so that they are compatible with your version of Python or upgrade to Python 3.5+ (I'd recommend the latter if possible, since support for Python 2.7 officially was ended this January).
