### ISSUE TITLE
Unable to install visualization

### ISSUE THREAD

**Issue by thomasweng15** [BerkeleyAutomation/visualization#3]
On an Ubuntu 16.04 machine in a clean python 2.7 or 3.5 virtual environment, I run `pip install visualization` and then `python -c "import visualization"` and get errors. In Python 2.7 I the following error: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "visualization/__init__.py", line 3, in <module>
    from .visualizer3d import Visualizer3D
  File "visualization/visualizer3d.py", line 11, in <module>
    import trimesh
  File "/usr0/home/tweng/.local/lib/python2.7/site-packages/trimesh/__init__.py", line 27, in <module>
    from .exchange.load import (load,
  File "/usr0/home/tweng/.local/lib/python2.7/site-packages/trimesh/exchange/load.py", line 16, in <module>
    from .assimp import _assimp_loaders
  File "/usr0/home/tweng/.local/lib/python2.7/site-packages/trimesh/exchange/assimp.py", line 130, in <module>
    import pyassimp
  File "/usr/lib/python2.7/dist-packages/pyassimp/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 29, in <module>
    class AssimpLib(object):
  File "/usr/lib/python2.7/dist-packages/pyassimp/core.py", line 34, in AssimpLib
    load, load_mem, release, dll = helper.search_library()
ValueError: need more than 3 values to unpack
```

On 3.5 I get the following error: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr0/home/tweng/envs/grasping_env_py3_1/lib/python3.5/site-packages/visualization/__init__.py", line 3, in <module>
    from .visualizer3d import Visualizer3D
  File "/usr0/home/tweng/envs/grasping_env_py3_1/lib/python3.5/site-packages/visualization/visualizer3d.py", line 15, in <module>
    from meshrender import Scene, SceneObject, InstancedSceneObject, AmbientLight, SceneViewer, MaterialProperties
  File "/usr0/home/tweng/envs/grasping_env_py3_1/lib/python3.5/site-packages/meshrender/__init__.py", line 11, in <module>
    from .viewer import SceneViewer
  File "/usr0/home/tweng/envs/grasping_env_py3_1/lib/python3.5/site-packages/meshrender/viewer.py", line 10, in <module>
    import pyglet.gl as gl
  File "/usr0/home/tweng/envs/grasping_env_py3_1/lib/python3.5/site-packages/pyglet/gl/__init__.py", line 227, in <module>
    del base
NameError: name 'base' is not defined
```

Have you encountered these errors before? Thanks for your help.

**Comment by jeffmahler** [comment]
@thomasweng15 I have seen the first error, not the second. In my experience, the pyassimp error happened due to a version mismatch between the assimp package available through Ubuntu package manager and the pyassimpy pypi package. You may want to try force updating one or the other.

Apparently [there is also a patch you can install](https://bugs.launchpad.net/ubuntu/+source/assimp/+bug/1589949).

@mmatl Have you seen the `name 'base' is not defined` issue with pyglet?
